# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "HaoliangZhou"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Multimodal Large Language Model":
        filters: ["Multimodal Large Language Model","Vision-Language Reasoning Model","Multimodal Chain-of-Thought Reasoning", "Multimodal Chain-of-Thought"]
    "Cross-Modal Image Retrieval":
        filters: ["Cross-Modal Image Retrieval","Cross-Modal Retrieval","Composed Image Retrieval", "Zero-shot Composed Image Retrieval"]
    "Continual Learning":
        filters: ["Continual Learning", "Incremental Learning", "Lifelong learning"]
    "Vision-Language Prompting":
        filters: ["Visual Prompt", "Text Prompt", "Vision-Language Prompt"]
    "Facial Expression Recognition":
        filters: ["Facial Expression Recognition", "Micro-Expression Recognition", "Micro Expression Recognition"]
    "Test-Time Adaptation":
        filters: ["Test-Time Adaptation", "Test Time Adaptation"]
